FROM node:24-bookworm-slim@sha256:0e0ff40c39bc087845bfb27465a0df4ea419520094bc35842ff83dd8cbe6f9b6
WORKDIR /app
COPY --chown=node:node src/ ./src/
COPY --chown=node:node workflow.yaml ./
USER node
CMD ["node", "src/install.mjs"]
